version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install buildstock
          command: |
            conda install -c conda-forge -y -q scipy numpy pandas "pyarrow>=0.14.1" dask joblib pyyaml
            pip install .[dev] --progress-bar off
      - run:
          name: Run PyTest
          command: |
            pytest -v
      - run:
          name: Run coverage tests
          when: always
          command: |
            set +e
            coverage run --source=buildstockbatch -m pytest > /dev/null 2>&1
            coverage report -m
            coverage html -d /tmp/coverage_report
      - run:
          name: Run style checks
          when: always
          command: |
            flake8 buildstockbatch
      - store_artifacts:
          path: /tmp/coverage_report
          destination: coverage-report
      - run:
          name: Build documentation
          when: always
          command: |
            apt-get install make
            cd docs
            make html
            mkdir /tmp/docs
            cp -r _build/html/* /tmp/docs
            if [ "$CIRCLE_BRANCH" = "master" ]
            then
            pip install awscli
            cd _build/html
            aws s3 rm s3://buildstock-batch --recursive
            aws s3 sync . s3://buildstock-batch
            fi
      - store_artifacts:
          path: /tmp/docs
          destination: docs
