version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: Install buildstock
          command: |
            sudo apt-get install libhdf5-serial-dev
            python3 -m venv env
            source env/bin/activate
            pip install .[dev] --progress-bar off
            pip install coverage --progress-bar off
      - run:
          name: Run PyTest
          command: |
            source env/bin/activate
            pytest
      - run:
          name: Run coverage tests
          when: always
          command: |
            set +e
            source env/bin/activate
            coverage run --source=buildstockbatch -m pytest > /dev/null 2>&1
            coverage report -m
            coverage html -d /tmp/coverage_report
      - run:
          name: Run style checks
          when: always
          command: |
            source env/bin/activate
            flake8 buildstockbatch
      - store_artifacts:
          path: /tmp/coverage_report
          destination: coverage-report